### ISSUE TITLE
convertView在换肤后创建,该view不会应用皮肤

### ISSUE THREAD

**Issue by cpoopc** [hongyangAndroid/AndroidChangeSkin#1]
这个换肤方案真赞!thanks a lot!!!
然后我发现个问题.
在demo中多加几个数据超过一屏,进入界面后不要滑动直接换肤.
此时converView未加入界面,所以不会换肤.就会出现convertView没有换肤的现象.
需要在新建converView后injectSkin.

```
SkinManager.getInstance().injectSkin(convertView);
```

**Comment by hongyangAndroid** [comment]
非常感谢反馈，其实我也想过这个问题，按照你说的代码即可，已经对外公布了injectSkin方法，后期可能会做缓存处理。

**Comment by cpoopc** [comment]
我突然发现似乎还有点不对，convertview即使创建了也不一定会在界面中。上面我说的那样还是解决不了问题

**Comment by hongyangAndroid** [comment]
恩，我更新了一下Demo，为ListView增加了大量的Item。目前使用如下的方式：

``` java
 if (convertView == null)
 {
       convertView = LayoutInflater.from(MainActivity.this).inflate(R.layout.item, parent, false);
 }
 SkinManager.getInstance().injectSkin(convertView);
```

欢迎更新demo查看，再次感谢反馈，后面可能会抽时间考虑下细节上的问题。

**Comment by cpoopc** [comment]
嗯，这样看来应该是没问题的。就是每次getview做这件事，当item复杂点，再快速滑动，不知道会不会有效率问题。可能得做点你说的缓存。
