### ISSUE TITLE
SkinManager中的mActivities对象会导致Activity的内存泄露么？

### ISSUE THREAD

**Issue by zhlu32** [hongyangAndroid/AndroidChangeSkin#2]
SkinManger作为单例对象，生命周期长，在如下两种情况下，会不会导致Activity回收不掉的问题？ 
1、Activity被销毁后，生命周期函数onDestory没被调用 （如使用clearTop方法的Intent）
2、如果内存紧张的情况下

可以优化成用SoftReference吧？

**Comment by hongyangAndroid** [comment]
问题1：如果Activity销毁了，对于这个前提，还怎么泄露呢？
问题2：这个也是对于1来说的吧~

**Comment by zhlu32** [comment]
我的意识是因为单例中持有activity的对象，会不会导致activity不能被回收？  前提是activity被销毁，但是没有调用到onDestory方法，导致activity对象没有被remove掉。

**Comment by hongyangAndroid** [comment]
恩，多谢提出意见，是这样的，你说的前提是activity出于某种被销毁了，也就是这个对象已经被销毁了，那么这个对象还如何泄露呢？  即使没有remove掉，对象不存在了，引用也没什么意义。不过对于SoftReference，可以考虑下。
