### ISSUE TITLE
请教关于selector、shape

### ISSUE THREAD

**Issue by huluwa-dev** [hongyangAndroid/AndroidChangeSkin#25]
大神，请教selector或者shape中引用的颜色如何修改呢？

**Comment by hackware1993** [comment]
@EricInCD 估计得重新写一份selector

**Comment by fanglingfeng** [comment]
我这里shape文件也无法生效，这个功能有没有啊

**Comment by ghost** [comment]
> 大神，请教selector或者shape中引用的颜色如何修改呢？

我已经加了扩展了，可以看下
https://github.com/hkdoke/changeskin_ex
